# Jupyter Notebook: Parsing CSV file and Visualizing Data

In this notebook, we will load a CSV file, convert it to a pandas DataFrame, and then create multiple city specific map visualizations using folium.

In [15]:
pip install pandas folium

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: folium in /opt/homebrew/lib/python3.11/site-packages (0.17.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: branca>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from folium) (0.8.0)
Requirement already satisfied: jinja2>=2.9 in /opt/homebrew/lib/python3.11/site-packages (from folium) (3.1.4)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/homebrew/lib/python3.11/site-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/lib/python3.11/site-packages (from jinja2>=2.9->folium) (3.0.1)
Requirement already satisfied: six>=1.5 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [16]:
# Import necessary libraries
import pandas as pd
import folium

## Step 1: Load CSV File

In [17]:
# Load the CSV file into a DataFrame
file_path = "colorado_food_pantries.csv"

df = pd.read_csv(file_path)

# Optional: Display the first few rows to check if the file is loaded correctly
df.head(15)

,Assistance Type,Agency,Address,City,State,Zip,County,Services,Eligibility,Hours,Phone,Website,Latitude,Longitude
0,Food Pantry,SILVER THREAD PUBLIC HEALTH DISTRICT,304 W 3rd St,Lake City,CO,81235,HINSDALE COUNTY,"Provides a food box to individuals, seniors an...",Individuals in the service area Area Served: H...,"Monday - Friday, 8 a.m. - 4:30 p.m.",(970) 944-0321,http://silverthreadpublichealth.org,38.028217,-107.314490
1,Food Pantry,PINE RIVER SHARES,658 S East St,Bayfield,CO,81122,LA PLATA COUNTY,Provides food for community members in need of...,Must be residents of Bayfield and the Pine Riv...,"Monday - Thursday, 9 a.m. - 3 p.m.",(970) 884-6040,http://pinerivershares.org,37.224047,-107.598306
2,Food Pantry,COMMUNITY UNITED METHODIST CHURCH OF PAGOSA SP...,434 Lewis St,Pagosa Springs,CO,81147,ARCHULETA COUNTY,Provides food to individuals and families in A...,No restrictions applied Area Served: Archuleta...,"Tuesday - Thursday, 8 a.m. - 12 p.m.",(970) 264-5508,http://cumcps.org,37.267823,-107.011796
3,Food Pantry,RESTORATION FELLOWSHIP,264 Village Dr,Pagosa Springs,CO,81147,ARCHULETA COUNTY,Provides food boxes for residents of Archuleta...,No restrictions. Area Served: Archuleta County,"Monday-Friday, 8:00am - 5:00pm",(970) 731-2937,http://restorationfellowship.net,37.258096,-107.075037
4,Food Pantry,OURAY COUNTY FOOD PANTRY,602 N Cora St,Ridgway,CO,81432,OURAY COUNTY,Provides groceries based on a shopping list fo...,Individuals must be a resident of Ouray County...,"Thursday, 12:30 pm - 3:30 pm",(970) 626-4273,http://ouraycountyfoodpantry.org,38.156621,-107.757265
5,Food Assistance,LOVE INC OF THE YAMPA VALLEY,1198 W Victory Way,Craig,CO,81625,MOFFAT COUNTY,Provides food to qualified individuals and fam...,"For TEFAP assistance, households must meet the...","3rd Tuesday, 10 a.m. - 12 p.m.; 3rd Thursday, ...",(970) 826-4400,http://loveincyampavalley.org/services,40.514264,-107.561261
6,Food Pantry,CONNECTIONS 4 LIFE,6436 S U.S. Hwy 85/87 Unit U,Colorado Springs,CO,80911,EL PASO COUNTY,Provides a food pantry to residents in need.,Residents of the service area Area Served: El ...,Hours Vary,(719) 387-9919,http://connections4lifecenter.org,38.745604,-104.738987
7,Food Pantry,GOD'S PANTRY MINISTRY,30 Widefield Blvd,Colorado Springs,CO,80911,EL PASO COUNTY,Provides a food pantry.,No restrictions applied Area Served: El Paso C...,"Monday - Saturday, 9 a.m. - 3 p.m.",(719) 382-0643,http://godspantryco.org,38.736079,-104.727113
8,Food Pantry,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides food box for Mesa County residents in...,No restrictions applied Area Served: Mesa County,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251
9,Food Assistance,WOODLAND PARK COMMUNITY CHURCH,700 Valley View Dr Unit D,Woodland Park,CO,80863,TELLER COUNTY,Provides emergency food necessities and delive...,No restrictions applied Area Served: Zip Codes...,"Monday - Thursday, 9 a.m. - 12 p.m.",(719) 229-4512,http://woodlandparkcommunitychurch.com/storehouse,39.012142,-105.062023
10,Food Pantry,LA PLATA FAMILY CENTERS COALITION,495 Florida Rd,Durango,CO,81301,LA PLATA COUNTY,Provides a food box to families in need in the...,"No restriction applied Area Served: La Plata, ...","Monday - Thursday, 8:30 a.m. - 4:30 p.m.; Frid...",(970) 385-4747,http://lpfcc.org,37.283861,-107.869957
11,Food Pantry,CENTER TOWARD SELF-RELIANCE,901 W 8th St,Pueblo,CO,81003,PUEBLO COUNTY,Food Pantry provides food assistance to low-in...,"Open to the Public, low-income individuals who...","Monday - Friday, 8 a.m. - 4:30 p.m.",(719) 546-1271,https://cfdpueblo.org,38.274091,-104.619700
12,Food Pantry,CITY OF COLORADO SPRINGS,4290 Deerfield Hills Rd,Colorado Springs,CO,80916,EL PASO COUNTY,Provides a drive-thru style food pantry to tho...,No restrictions applied Area Served: El Paso C...,"Monday - Friday, 9 a.m. - 6 p.m.",(719) 385-5996,http://coloradosprings.gov/deeraeld-hills-comm...,38.784574,-104.747881
13,Food Pantry,NEW LIFE COMMUNITY CHURCH,17690 E Iliff Ave,Aurora,CO,80013,ARAPAHOE COUNTY,Provides bags of food to the community. The pa...,"No restrictions applied Area Served: Adams, Ar...","Tuesday, 1 p.m. - 4 p.m.; Saturday, 10 a.m. - ...",(303) 368-7567,http://nlccaurora.org,39.674607,-104.778200
14,Pet Food Pantry Locator,COLORADO PET PANTRY,P.O. Box 323,Boulder,CO,80306,BOULDER COUNTY,Provides free temporary pet food through vario...,No restrictions applied Area Served: Statewide,"Monday - Sunday, 9 a.m. - 5 p.m. (Administrati...",(303) 818-0618,http://coloradopetpantry.org/events/category/p...,40.102555,-105.363208

## Step 2: Clean and Prepare the Data

In [18]:
# Check column names and data types
df.info()

# Clean any missing latitude or longitude data
df.dropna(subset=['Longitude', 'Latitude'], inplace=True)

# Optional: Check for missing values in other important columns
df.isnull().sum()

# Optional: Display the first few rows of cleaned data
df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 443 entries, 0 to 442
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Assistance Type  443 non-null    object
 1   Agency           443 non-null    object
 2   Address          443 non-null    object
 3   City             443 non-null    object
 4   State            443 non-null    object
 5   Zip              443 non-null    int64
 6   County           443 non-null    object
 7   Services         443 non-null    object
 8   Eligibility      443 non-null    object
 9   Hours            443 non-null    object
 10  Phone            443 non-null    object
 11  Website          443 non-null    object
 12  Latitude         443 non-null    float64
 13  Longitude        443 non-null    float64
dtypes: float64(2), int64(1), object(11)
memory usage: 48.6+ KB

,Assistance Type,Agency,Address,City,State,Zip,County,Services,Eligibility,Hours,Phone,Website,Latitude,Longitude
0,Food Pantry,SILVER THREAD PUBLIC HEALTH DISTRICT,304 W 3rd St,Lake City,CO,81235,HINSDALE COUNTY,"Provides a food box to individuals, seniors an...",Individuals in the service area Area Served: H...,"Monday - Friday, 8 a.m. - 4:30 p.m.",(970) 944-0321,http://silverthreadpublichealth.org,38.028217,-107.314490
1,Food Pantry,PINE RIVER SHARES,658 S East St,Bayfield,CO,81122,LA PLATA COUNTY,Provides food for community members in need of...,Must be residents of Bayfield and the Pine Riv...,"Monday - Thursday, 9 a.m. - 3 p.m.",(970) 884-6040,http://pinerivershares.org,37.224047,-107.598306
2,Food Pantry,COMMUNITY UNITED METHODIST CHURCH OF PAGOSA SP...,434 Lewis St,Pagosa Springs,CO,81147,ARCHULETA COUNTY,Provides food to individuals and families in A...,No restrictions applied Area Served: Archuleta...,"Tuesday - Thursday, 8 a.m. - 12 p.m.",(970) 264-5508,http://cumcps.org,37.267823,-107.011796
3,Food Pantry,RESTORATION FELLOWSHIP,264 Village Dr,Pagosa Springs,CO,81147,ARCHULETA COUNTY,Provides food boxes for residents of Archuleta...,No restrictions. Area Served: Archuleta County,"Monday-Friday, 8:00am - 5:00pm",(970) 731-2937,http://restorationfellowship.net,37.258096,-107.075037
4,Food Pantry,OURAY COUNTY FOOD PANTRY,602 N Cora St,Ridgway,CO,81432,OURAY COUNTY,Provides groceries based on a shopping list fo...,Individuals must be a resident of Ouray County...,"Thursday, 12:30 pm - 3:30 pm",(970) 626-4273,http://ouraycountyfoodpantry.org,38.156621,-107.757265
5,Food Assistance,LOVE INC OF THE YAMPA VALLEY,1198 W Victory Way,Craig,CO,81625,MOFFAT COUNTY,Provides food to qualified individuals and fam...,"For TEFAP assistance, households must meet the...","3rd Tuesday, 10 a.m. - 12 p.m.; 3rd Thursday, ...",(970) 826-4400,http://loveincyampavalley.org/services,40.514264,-107.561261
6,Food Pantry,CONNECTIONS 4 LIFE,6436 S U.S. Hwy 85/87 Unit U,Colorado Springs,CO,80911,EL PASO COUNTY,Provides a food pantry to residents in need.,Residents of the service area Area Served: El ...,Hours Vary,(719) 387-9919,http://connections4lifecenter.org,38.745604,-104.738987
7,Food Pantry,GOD'S PANTRY MINISTRY,30 Widefield Blvd,Colorado Springs,CO,80911,EL PASO COUNTY,Provides a food pantry.,No restrictions applied Area Served: El Paso C...,"Monday - Saturday, 9 a.m. - 3 p.m.",(719) 382-0643,http://godspantryco.org,38.736079,-104.727113
8,Food Pantry,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides food box for Mesa County residents in...,No restrictions applied Area Served: Mesa County,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251
9,Food Assistance,WOODLAND PARK COMMUNITY CHURCH,700 Valley View Dr Unit D,Woodland Park,CO,80863,TELLER COUNTY,Provides emergency food necessities and delive...,No restrictions applied Area Served: Zip Codes...,"Monday - Thursday, 9 a.m. - 12 p.m.",(719) 229-4512,http://woodlandparkcommunitychurch.com/storehouse,39.012142,-105.062023
10,Food Pantry,LA PLATA FAMILY CENTERS COALITION,495 Florida Rd,Durango,CO,81301,LA PLATA COUNTY,Provides a food box to families in need in the...,"No restriction applied Area Served: La Plata, ...","Monday - Thursday, 8:30 a.m. - 4:30 p.m.; Frid...",(970) 385-4747,http://lpfcc.org,37.283861,-107.869957
11,Food Pantry,CENTER TOWARD SELF-RELIANCE,901 W 8th St,Pueblo,CO,81003,PUEBLO COUNTY,Food Pantry provides food assistance to low-in...,"Open to the Public, low-income individuals who...","Monday - Friday, 8 a.m. - 4:30 p.m.",(719) 546-1271,https://cfdpueblo.org,38.274091,-104.619700
12,Food Pantry,CITY OF COLORADO SPRINGS,4290 Deerfield Hills Rd,Colorado Springs,CO,80916,EL PASO COUNTY,Provides a drive-thru style food pantry to tho...,No restrictions applied Area Served: El Paso C...,"Monday - Friday, 9 a.m. - 6 p.m.",(719) 385-5996,http://coloradosprings.gov/deeraeld-hills-comm...,38.784574,-104.747881
13,Food Pantry,NEW LIFE COMMUNITY CHURCH,17690 E Iliff Ave,Aurora,CO,80013,ARAPAHOE COUNTY,Provides bags of food to the community. The pa...,"No restrictions applied Area Served: Adams, Ar...","Tuesday, 1 p.m. - 4 p.m.; Saturday, 10 a.m. - ...",(303) 368-7567,http://nlccaurora.org,39.674607,-104.778200
14,Pet Food Pantry Locator,COLORADO PET PANTRY,P.O. Box 323,Boulder,CO,80306,BOULDER COUNTY,Provides free temporary pet food through vario...,No restrictions applied Area Served: Statewide,"Monday - Sunday, 9 a.m. - 5 p.m. (Administrati...",(303) 818-0618,http://coloradopetpantry.org/events/category/p...,40.102555,-105.363208

## Step 3: Create a Searchable Map

In [19]:
# Initialize the map centered around Colorado
m = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

# Add markers to the map for each food pantry
for idx, row in df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m)

# Save the map as an HTML file
m.save("colorado_food_pantries_map_v2.html")

# Display the map in the notebook
m

## Step 4: Implement Search Functionality

In [20]:
# Example: Search for food pantries in a specific city
city_search = "Denver"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_denver_v2.html")

# Display the filtered map in the notebook
m_filtered

In [21]:
# Example: Search for food pantries in a specific city
city_search = "Colorado Springs"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.8591, -104.8135], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_colorado_springs_v2.html")

# Display the filtered map in the notebook
m_filtered

In [22]:
# Example: Search for food pantries in a specific city
city_search = "Aurora"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7108, -104.8125], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_aurora_v2.html")

# Display the filtered map in the notebook
m_filtered

In [23]:
# Example: Search for food pantries in a specific city
city_search = "Fort Collins"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.5853, -105.0844], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_fort_collins_v2.html")

# Display the filtered map in the notebook
m_filtered

In [24]:
# Example: Search for food pantries in a specific city
city_search = "Lakewood"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7109, -105.0815], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_lakewood_v2.html")

# Display the filtered map in the notebook
m_filtered

In [25]:
# Example: Search for food pantries in a specific city
city_search = "Arvada"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.8028, -105.0875], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_arvada_v2.html")

# Display the filtered map in the notebook
m_filtered

In [26]:
# Example: Search for food pantries in a specific city
city_search = "Greeley"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.4233, -104.7112], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_greeley_v2.html")

# Display the filtered map in the notebook
m_filtered

In [27]:
# Example: Search for food pantries in a specific city
city_search = "Pueblo"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.2765, -104.6046], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_pueblo_v2.html")

# Display the filtered map in the notebook
m_filtered

In [28]:
# Example: Search for food pantries in a specific city
city_search = "Boulder"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.0150, -105.2705], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_boulder_v2.html")

# Display the filtered map in the notebook
m_filtered

In [29]:
# Example: Search for food pantries in a specific city
city_search = "Grand Junction"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.0714, -108.5497], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_food_pantries_map_grand_junction_v2.html")

# Display the filtered map in the notebook
m_filtered

## Step 5: Export Cleaned Data to CSV

In [30]:
# Export the cleaned DataFrame to a CSV file
df.to_csv("cleaned_colorado_food_pantries_v3.csv", index=False)

# Confirm the export
print("Data exported to cleaned_colorado_food_pantries_v3.csv")

Data exported to cleaned_colorado_food_pantries_v3.csv