# Jupyter Notebook: Parsing CSV file and Visualizing Data

In this notebook, we will load a CSV file, convert it to a pandas DataFrame, and then create multiple city specific map visualizations using folium.

In [1]:
pip install pandas folium

Requirement already satisfied: pandas in /opt/homebrew/lib/python3.11/site-packages (2.2.3)
Requirement already satisfied: folium in /opt/homebrew/lib/python3.11/site-packages (0.17.0)
Requirement already satisfied: numpy>=1.23.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/lib/python3.11/site-packages (from pandas) (2024.2)
Requirement already satisfied: branca>=0.6.0 in /opt/homebrew/lib/python3.11/site-packages (from folium) (0.8.0)
Requirement already satisfied: jinja2>=2.9 in /opt/homebrew/lib/python3.11/site-packages (from folium) (3.1.4)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.11/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/homebrew/lib/python3.11/site-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/homebrew/lib/python3.11/site-packages (from jinja2>=2.9->folium) (3.0.1)
Requirement already satisfied: six>=1.5 in /Users/ceraven/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Import necessary libraries
import pandas as pd
import folium

## Step 1: Load CSV File

In [4]:
# Load the CSV file into a DataFrame
file_path = "colorado_housing_assistance.csv"

df = pd.read_csv(file_path)

# Optional: Display the first few rows to check if the file is loaded correctly
df.head(15)

,Assistance,Agency,Address,City,State,Zip,County,Services,Eligibility,Hours,Phone,Website,Latitude,Longitude
0,Temporary Overnight Shelter,FAMILY HOUSING NETWORK,1606 S Lemay Ave Suite 103,Fort Collins,CO,80525,LARIMER COUNTY,Provides a temporary overnight shelter for fam...,Eligibility: Eligible adults must:Have at leas...,"Monday - Friday, 9 a.m. - 5 p.m. (Administrati...",(970) 484-3342,http://familyhousingnetwork.org/our-programs,40.566559,-105.056925
1,Veteran Housing Transitional Housing Program,VOLUNTEERS OF AMERICA COLORADO,1055 Avenida Del Sol,Durango,CO,81301,LA PLATA COUNTY,Provides veterans and their families shelter a...,Eligibility: Veterans aged 18 and older who ar...,"Monday - Friday, 8 a.m. - 5 p.m. (Administrati...",(970) 259-1255,http://voacolorado.org/gethelp-southernco-veth...,37.276682,-107.884155
2,Substance Abuse Services,A WAY OUT,PO Box 1124,Carbondale,CO,81623,PITKIN COUNTY,Offers services that helps those suffering fro...,Eligibility: Individuals must be a resident of...,"Monday - Friday, 9 a.m. - 5 p.m.",(970) 340-4505,http://awayout.org,39.400565,-107.211241
3,Homeless Motel Assistance,CARING & SHARING SALIDA,220 W 4th St,Salida,CO,81201,CHAFFEE COUNTY,Provide short-term emergency housing on a case...,Eligibility: Individuals and families experien...,"Monday - Saturday, 10:30 a.m. - 1:30 p.m.",(719) 539-4849,http://salidacaringsharing.org,38.534785,-105.996096
4,Housing for Pregnant Women and Women with Chil...,CATHOLIC CHARITIES OF DENVER,6240 Smith Rd,Denver,CO,80207,DENVER COUNTY,Provides housing and supportive services for p...,Eligibility: Pregnant women and female-identif...,"Monday - Thursday, 8 a.m. - 5 p.m.; Friday, 8:...",(720) 799-9400,http://ccdenver.org/marisolservices/marisol-ho...,39.775396,-104.942292
5,Transitional Shelter for Single Women,CATHOLIC CHARITIES OF DENVER,2301 Lawrence St,Denver,CO,80205,DENVER COUNTY,Provides shelter for up to 6 months for single...,Eligibility: Single women aged 18 and older Ar...,"Monday - Friday, 8:30 a.m. - 5 p.m. (Administr...",(720) 799-9506 (Samaritan House at 48th),No Website Listed,39.755651,-104.987200
6,Transitional Housing,DREAM CENTERS,3650 Airport Rd,Colorado Springs,CO,80910,EL PASO COUNTY,Provides transitional housing for homeless or ...,Eligibility: Homeless or imminently homeless w...,24 hours/7 days a week,(719) 301-5411,http://dreamcenters.com/marys-home/apply/,38.825542,-104.765124
7,Overflow Shelter for Single Women & Families,CATHOLIC CHARITIES LARIMER COUNTY,460 Linden Center Dr,Fort Collins,CO,80524,LARIMER COUNTY,"Provides nightly, year-round overnight shelter...",Eligibility: Female gender served only. There ...,"Monday - Friday, 8:30 a.m. - 12 p.m., 1 p.m. -...",(970) 493-0141 (Shelter),http://ccdenver.org/larimer/,40.594737,-105.069211
8,Shelter for Families,HOPE @ MIRACLE HOUSE,Main Street,Fort Lupton,CO,80621,WELD COUNTY,Seeks to address the needs of homeless familie...,Eligibility: Families experiencing homelessnes...,Hours Vary,(720) 676-9697 (Message Line),http://hopeatmiraclehouse.org,40.079786,-104.809698
9,Transitional Housing for Single Adults,ITHAKA HOUSING,321 Mesa Rd,Colorado Springs,CO,80905,EL PASO COUNTY,"Provides transitional housing, in a group home...",Eligibility: Individuals must: Be single men (...,"Monday - Thursday, 8 a.m. - 5 p.m.",(719) 578-1629,http://ithakaland.org,38.845795,-104.831625
10,Drop-In Center,MILE HIGH BEHAVIORAL HEALTHCARE,13387 E 19th Pl,Aurora,CO,80011,ADAMS COUNTY,Provides the following drop-in services: Break...,Eligibility: No restrictions applied Area Serv...,"Monday - Friday, 7:30 a.m. - 4:30 p.m. (Drop-I...",(303) 341-9160,http://comitiscrisiscenter.org/aurora-day-reso...,39.746673,-104.831612
11,Transitional Housing,HASEYA ADVOCATE PROGRAM,I-25,Colorado Springs,CO,80903,EL PASO COUNTY,Provides transitional housing for Native Ameri...,Eligibility: Available to Native American surv...,"Monday, Wednesday, Thursday 9:00 a.m. - 3:00 p...",(719) 660-3939,http://haseya.org,38.838192,-104.830329
12,Transitional Housing for Young Men,PROVIDENCE NETWORK,801 Logan St,Denver,CO,80203,DENVER COUNTY,Provides transitional housing and wrap-around ...,Eligibility: Young men aged 18 - 25 years and ...,"Monday - Friday, 8 a.m. - 5 p.m. (Administrati...",(303) 860-8404,http://providencenetwork.org,39.729339,-104.982719
13,Transitional Supportive Housing,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides individuals with the opportunity to e...,Eligibility: Individuals experiencing homeless...,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251
14,Permanent Supportive Housing,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides homes to those with mental or physica...,Eligibility: Individuals and families living w...,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251

## Step 2: Clean and Prepare the Data

In [5]:
# Check column names and data types
df.info()

# Clean any missing latitude or longitude data
df.dropna(subset=['Longitude', 'Latitude'], inplace=True)

# Optional: Check for missing values in other important columns
df.isnull().sum()

# Optional: Display the first few rows of cleaned data
df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Assistance   114 non-null    object
 1   Agency       114 non-null    object
 2   Address      114 non-null    object
 3   City         114 non-null    object
 4   State        114 non-null    object
 5   Zip          114 non-null    int64
 6   County       114 non-null    object
 7   Services     114 non-null    object
 8   Eligibility  114 non-null    object
 9   Hours        114 non-null    object
 10  Phone        114 non-null    object
 11  Website      114 non-null    object
 12  Latitude     114 non-null    float64
 13  Longitude    114 non-null    float64
dtypes: float64(2), int64(1), object(11)
memory usage: 12.6+ KB

,Assistance,Agency,Address,City,State,Zip,County,Services,Eligibility,Hours,Phone,Website,Latitude,Longitude
0,Temporary Overnight Shelter,FAMILY HOUSING NETWORK,1606 S Lemay Ave Suite 103,Fort Collins,CO,80525,LARIMER COUNTY,Provides a temporary overnight shelter for fam...,Eligibility: Eligible adults must:Have at leas...,"Monday - Friday, 9 a.m. - 5 p.m. (Administrati...",(970) 484-3342,http://familyhousingnetwork.org/our-programs,40.566559,-105.056925
1,Veteran Housing Transitional Housing Program,VOLUNTEERS OF AMERICA COLORADO,1055 Avenida Del Sol,Durango,CO,81301,LA PLATA COUNTY,Provides veterans and their families shelter a...,Eligibility: Veterans aged 18 and older who ar...,"Monday - Friday, 8 a.m. - 5 p.m. (Administrati...",(970) 259-1255,http://voacolorado.org/gethelp-southernco-veth...,37.276682,-107.884155
2,Substance Abuse Services,A WAY OUT,PO Box 1124,Carbondale,CO,81623,PITKIN COUNTY,Offers services that helps those suffering fro...,Eligibility: Individuals must be a resident of...,"Monday - Friday, 9 a.m. - 5 p.m.",(970) 340-4505,http://awayout.org,39.400565,-107.211241
3,Homeless Motel Assistance,CARING & SHARING SALIDA,220 W 4th St,Salida,CO,81201,CHAFFEE COUNTY,Provide short-term emergency housing on a case...,Eligibility: Individuals and families experien...,"Monday - Saturday, 10:30 a.m. - 1:30 p.m.",(719) 539-4849,http://salidacaringsharing.org,38.534785,-105.996096
4,Housing for Pregnant Women and Women with Chil...,CATHOLIC CHARITIES OF DENVER,6240 Smith Rd,Denver,CO,80207,DENVER COUNTY,Provides housing and supportive services for p...,Eligibility: Pregnant women and female-identif...,"Monday - Thursday, 8 a.m. - 5 p.m.; Friday, 8:...",(720) 799-9400,http://ccdenver.org/marisolservices/marisol-ho...,39.775396,-104.942292
5,Transitional Shelter for Single Women,CATHOLIC CHARITIES OF DENVER,2301 Lawrence St,Denver,CO,80205,DENVER COUNTY,Provides shelter for up to 6 months for single...,Eligibility: Single women aged 18 and older Ar...,"Monday - Friday, 8:30 a.m. - 5 p.m. (Administr...",(720) 799-9506 (Samaritan House at 48th),No Website Listed,39.755651,-104.987200
6,Transitional Housing,DREAM CENTERS,3650 Airport Rd,Colorado Springs,CO,80910,EL PASO COUNTY,Provides transitional housing for homeless or ...,Eligibility: Homeless or imminently homeless w...,24 hours/7 days a week,(719) 301-5411,http://dreamcenters.com/marys-home/apply/,38.825542,-104.765124
7,Overflow Shelter for Single Women & Families,CATHOLIC CHARITIES LARIMER COUNTY,460 Linden Center Dr,Fort Collins,CO,80524,LARIMER COUNTY,"Provides nightly, year-round overnight shelter...",Eligibility: Female gender served only. There ...,"Monday - Friday, 8:30 a.m. - 12 p.m., 1 p.m. -...",(970) 493-0141 (Shelter),http://ccdenver.org/larimer/,40.594737,-105.069211
8,Shelter for Families,HOPE @ MIRACLE HOUSE,Main Street,Fort Lupton,CO,80621,WELD COUNTY,Seeks to address the needs of homeless familie...,Eligibility: Families experiencing homelessnes...,Hours Vary,(720) 676-9697 (Message Line),http://hopeatmiraclehouse.org,40.079786,-104.809698
9,Transitional Housing for Single Adults,ITHAKA HOUSING,321 Mesa Rd,Colorado Springs,CO,80905,EL PASO COUNTY,"Provides transitional housing, in a group home...",Eligibility: Individuals must: Be single men (...,"Monday - Thursday, 8 a.m. - 5 p.m.",(719) 578-1629,http://ithakaland.org,38.845795,-104.831625
10,Drop-In Center,MILE HIGH BEHAVIORAL HEALTHCARE,13387 E 19th Pl,Aurora,CO,80011,ADAMS COUNTY,Provides the following drop-in services: Break...,Eligibility: No restrictions applied Area Serv...,"Monday - Friday, 7:30 a.m. - 4:30 p.m. (Drop-I...",(303) 341-9160,http://comitiscrisiscenter.org/aurora-day-reso...,39.746673,-104.831612
11,Transitional Housing,HASEYA ADVOCATE PROGRAM,I-25,Colorado Springs,CO,80903,EL PASO COUNTY,Provides transitional housing for Native Ameri...,Eligibility: Available to Native American surv...,"Monday, Wednesday, Thursday 9:00 a.m. - 3:00 p...",(719) 660-3939,http://haseya.org,38.838192,-104.830329
12,Transitional Housing for Young Men,PROVIDENCE NETWORK,801 Logan St,Denver,CO,80203,DENVER COUNTY,Provides transitional housing and wrap-around ...,Eligibility: Young men aged 18 - 25 years and ...,"Monday - Friday, 8 a.m. - 5 p.m. (Administrati...",(303) 860-8404,http://providencenetwork.org,39.729339,-104.982719
13,Transitional Supportive Housing,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides individuals with the opportunity to e...,Eligibility: Individuals experiencing homeless...,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251
14,Permanent Supportive Housing,GRAND VALLEY CATHOLIC OUTREACH,245 S 1st St,Grand Junction,CO,81501,MESA COUNTY,Provides homes to those with mental or physica...,Eligibility: Individuals and families living w...,"Monday - Friday, 9 a.m. - 11:30 a.m.",(970) 241-3658,http://catholicoutreach.org,39.065587,-108.571251

## Step 3: Create a Searchable Map

In [6]:
# Initialize the map centered around Colorado
m = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

# Add markers to the map for each housing assistance location
for idx, row in df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m)

# Save the map as an HTML file
m.save("colorado_housing_assistance_map_v2.html")

# Display the map in the notebook
m

## Step 4: Implement Search Functionality

In [8]:
# Example: Search for housing assistance in a specific city
city_search = "Denver"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.5501, -105.7821], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_denver_v2.html")

# Display the filtered map in the notebook
m_filtered

In [9]:
# Example: Search for housing assistance in a specific city
city_search = "Colorado Springs"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.8591, -104.8135], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_colorado_springs_v2.html")

# Display the filtered map in the notebook
m_filtered

In [10]:
# Example: Search for housing assistance in a specific city
city_search = "Aurora"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7108, -104.8125], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_aurora_v2.html")

# Display the filtered map in the notebook
m_filtered

In [12]:
# Example: Search for housing assistance in a specific city
city_search = "Fort Collins"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.5853, -105.0844], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_fort_collins_v2.html")

# Display the filtered map in the notebook
m_filtered

In [13]:
# Example: Search for housing assistance in a specific city
city_search = "Lakewood"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.7109, -105.0815], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_lakewood_v2.html")

# Display the filtered map in the notebook
m_filtered

In [14]:
# Example: Search for housing assistance in a specific city
city_search = "Arvada"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.8028, -105.0875], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_arvada_v2.html")

# Display the filtered map in the notebook
m_filtered

In [15]:
# Example: Search for housing assistance in a specific city
city_search = "Greeley"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.4233, -104.7112], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_greeley_v2.html")

# Display the filtered map in the notebook
m_filtered

In [16]:
# Example: Search for housing assistance in a specific city
city_search = "Pueblo"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[38.2765, -104.6046], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_pueblo_v2.html")

# Display the filtered map in the notebook
m_filtered

In [17]:
# Example: Search for housing assistance in a specific city
city_search = "Boulder"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[40.0150, -105.2705], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_boulder_v2.html")

# Display the filtered map in the notebook
m_filtered

In [18]:
# Example: Search for housing assistance in a specific city
city_search = "Grand Junction"  # Replace with user input

# Filter the DataFrame based on the city
filtered_df = df[df['City'].str.contains(city_search, case=False, na=False)]

# Create a map for the filtered results
m_filtered = folium.Map(location=[39.0714, -108.5497], zoom_start=7)

for idx, row in filtered_df.iterrows():
    popup_text = f"""
    <strong>{row['Agency']}</strong><br>
    {row['Address']}<br>
    {row['City']}, {row['State']} {row['Zip']}<br>
    <b>Phone:</b><br><a href="tel:{row['Phone']}">{row['Phone']}</a><br>
    <b>Website:</b><br> <a href="{row['Website']}">{row['Agency']}</a><br>
    <b>Services:</b><br> {row['Services']}
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_text,
    ).add_to(m_filtered)

# Save the filtered map as an HTML file
m_filtered.save("filtered_colorado_housing_assistance_map_grand_junction_v2.html")

# Display the filtered map in the notebook
m_filtered

## Step 5: Export Cleaned Data to CSV

In [19]:
# Export the cleaned DataFrame to a CSV file
df.to_csv("cleaned_colorado_housing_assistance_v3.csv", index=False)

# Confirm the export
print("Data exported to cleaned_colorado_housing_assistance_v3.csv")

Data exported to cleaned_colorado_housing_assistance_v3.csv